default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: pizza_server_development

test:
  <<: *default
  database: pizza_server_test

production:
  <<: *default
  database: pizza_server_production
